-- Logico_v2_ViagensBSI:

BEGIN;

CREATE TABLE SOLICITACAO_VIAGEM (
    id SERIAL UNIQUE NOT NULL,
    nome VARCHAR(150),
    orcamento_minimo DECIMAL,
    data_partida DATE,
    data_retorno DATE,
    descricao_preferencias_passeio TEXT,
    descricao_preferencias_voo TEXT,
    descricao_preferencias_hospedagem TEXT,
    descricao_perfil_grupo TEXT,
    orcamento_maximo DECIMAL,
    id_cidade_origem INTEGER,
    id_cidade_destino INTEGER,
    id_cliente_responsavel INTEGER
);

CREATE TABLE PACOTE_VIAGEM (
    id SERIAL UNIQUE NOT NULL,
    foi_escolhido BOOLEAN DEFAULT false NOT NULL,
    id_solicitacao_viagem INTEGER NOT NULL
);

CREATE TABLE EMPRESA (
    id SERIAL NOT NULL UNIQUE,
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    id_ramo_empresa INTEGER NOT NULL,
    id_endereco INTEGER
);

CREATE TABLE RESERVA_QUARTO (
    id SERIAL UNIQUE NOT NULL,
    numero_quarto VARCHAR(255),
    data_checkin DATE,
    hora_checkin TIME,
    previsao_dias_hospedagem INTEGER,
    data_previsao_checkout DATE,
    hora_previsao_checkout TIME,
    valor_diaria DECIMAL,
    id_pacote_viagem INTEGER,
    id_hospedaria INTEGER
);

CREATE TABLE HOSPEDARIA (
    id SERIAL UNIQUE NOT NULL,
    descricao TEXT,
    numero_estrelas INTEGER,
    link_website VARCHAR(255)
);

CREATE TABLE TIPO_VEICULO (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE RAMO_EMPRESA (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL UNIQUE,
    UNIQUE (descricao, id)
);

CREATE TABLE RESERVA_VEICULO (
    id SERIAL UNIQUE NOT NULL,
    numero_veiculo VARCHAR(255),
    placa_veiculo VARCHAR(255),
    preco_diaria DECIMAL,
    data_inicio DATE,
    hora_inicio TIME,
    previsao_dias_aluguel INTEGER,
    data_previsao_entrega DATE,
    hora_previsao_entrega TIME,
    id_pacote_viagem INTEGER,
    id_tipo_veiculo INTEGER,
    id_empresa_locadora INTEGER
);

CREATE TABLE PASSEIO (
    id SERIAL NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    id_endereco INTEGER
);

CREATE TABLE ENDERECO (
    id SERIAL NOT NULL UNIQUE,
    logradouro VARCHAR(255),
    numero INTEGER,
    complemento VARCHAR(255),
    cep VARCHAR(8),
    id_cidade INTEGER NOT NULL
);

CREATE TABLE CIDADE (
    id SERIAL NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    id_estado INTEGER NOT NULL
);

CREATE TABLE ESTADO (
    id SERIAL UNIQUE NOT NULL,
    nome VARCHAR(100),
    sigla VARCHAR(5) UNIQUE
);

CREATE TABLE BENEFICIO_HOSPEDAGEM (
    id SERIAL NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL UNIQUE,
    UNIQUE (nome, id)
);

CREATE TABLE PASSAGEM_AEREA (
    id SERIAL NOT NULL UNIQUE,
    numero_voo VARCHAR(255),
    numero_passagem VARCHAR(255) UNIQUE,
    numero_assento VARCHAR(255),
    data_decolagem DATE,
    horario_decolagem TIME,
    data_pouso DATE,
    horario_pouso TIME,
    id_cliente_titular INTEGER,
    id_companhia_aerea INTEGER
);

CREATE TABLE TIPO_DOCUMENTO (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE TIPO_NECESSIDADE_ESPECIAL (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE CLIENTE (
    id SERIAL NOT NULL UNIQUE,
    data_nascimento DATE,
    nome_social VARCHAR(150) NOT NULL,
    nome_registro VARCHAR(150) 
);

CREATE TABLE TIPO_CONTATO (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE STATUS (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(40) NOT NULL UNIQUE,
    UNIQUE (descricao, id)
);

CREATE TABLE PAGAMENTO (
    id SERIAL NOT NULL UNIQUE,
    valor DECIMAL NOT NULL,
    desconto DECIMAL,
    qtd_parcelas INTEGER DEFAULT 1,
    data_hora_pagamento TIMESTAMP,
    id_metodo_pagamento INTEGER NOT NULL,
    id_pacote_viagem INTEGER NOT NULL
);

CREATE TABLE METODO_PAGAMENTO (
    id SERIAL NOT NULL UNIQUE,
    descricao VARCHAR(70) NOT NULL UNIQUE
);

CREATE TABLE EMPRESA_VEICULO (
    id_empresa INTEGER NOT NULL,
    id_tipo_veiculo INTEGER NOT NULL
);

CREATE TABLE BENEFICIO_HOSPEDARIA (
    id_hospedaria INTEGER NOT NULL,
    id_beneficio_hospedagem INTEGER NOT NULL
);

CREATE TABLE EMPRESA_PASSEIO (
    id_passeio INTEGER NOT NULL,
    id_empresa INTEGER NOT NULL,
    preco DECIMAL
);

CREATE TABLE PASSAGEM_AEREA_VIAGEM (
    id_pacote_viagem INTEGER NOT NULL,
    id_passagem_aerea INTEGER NOT NULL
);

CREATE TABLE DOCUMENTO_CLIENTE (
    id_tipo_documento INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    numero_documento VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE NECESSIDADE_ESPECIAL_CLIENTE (
    id_cliente INTEGER NOT NULL,
    id_necessidade_especial INTEGER NOT NULL
);

CREATE TABLE CONTATO_CLIENTE_RESPONSAVEL (
    id_tipo_contato INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    descricao VARCHAR(100) NOT NULL
);

CREATE TABLE AGENDA_PASSEIO_VIAGEM (
    id_pacote_viagem INTEGER NOT NULL,
    id_passeio INTEGER NOT NULL,
    hora TIME,
    data DATE
);

CREATE TABLE CONTATO_EMPRESA (
    id_tipo_contato INTEGER NOT NULL,
    id_empresa INTEGER NOT NULL,
    descricao VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE ACOMPANHANTE_VIAGEM (
    id_cliente INTEGER NOT NULL,
    id_solicitacao_viagem INTEGER NOT NULL
);

CREATE TABLE SITUACAO_ATENDIMENTO (
    id_solicitacao_viagem INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    data_hora_mudanca TIMESTAMP NOT NULL
);

CREATE TABLE PROCURA_VEICULO_VIAGEM (
    id_tipo_veiculo INTEGER NOT NULL,
    id_solicitacao_viagem INTEGER NOT NULL
);

-- Adicionando as constraints para a tabela SOLICITACAO_VIAGEM
ALTER TABLE SOLICITACAO_VIAGEM ADD CONSTRAINT PK_SOLICITACAO_VIAGEM
    PRIMARY KEY (id);

ALTER TABLE SOLICITACAO_VIAGEM ADD CONSTRAINT FK_SOLICITACAO_VIAGEM_CIDADE_ORIGEM
    FOREIGN KEY (id_cidade_origem)
    REFERENCES CIDADE (id);

ALTER TABLE SOLICITACAO_VIAGEM ADD CONSTRAINT FK_SOLICITACAO_VIAGEM_CIDADE_DESTINO
    FOREIGN KEY (id_cidade_destino)
    REFERENCES CIDADE (id);

ALTER TABLE SOLICITACAO_VIAGEM ADD CONSTRAINT FK_SOLICITACAO_VIAGEM_CLIENTE_RESPONSAVEL
    FOREIGN KEY (id_cliente_responsavel)
    REFERENCES CLIENTE (id);

-- Adicionando as constraints para a tabela PACOTE_VIAGEM
ALTER TABLE PACOTE_VIAGEM ADD CONSTRAINT PK_PACOTE_VIAGEM
    PRIMARY KEY (id);

ALTER TABLE PACOTE_VIAGEM ADD CONSTRAINT FK_PACOTE_VIAGEM_SOLICITACAO_VIAGEM
    FOREIGN KEY (id_solicitacao_viagem)
    REFERENCES SOLICITACAO_VIAGEM (id);

-- Adicionando as constraints para a tabela EMPRESA
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA
    PRIMARY KEY (id);

ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_RAMO_EMPRESA
    FOREIGN KEY (id_ramo_empresa)
    REFERENCES RAMO_EMPRESA (id);

ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_ENDERECO
    FOREIGN KEY (id_endereco)
    REFERENCES ENDERECO (id);

-- Adicionando as constraints para a tabela RESERVA_QUARTO
ALTER TABLE RESERVA_QUARTO ADD CONSTRAINT PK_RESERVA_QUARTO
    PRIMARY KEY (id);

ALTER TABLE RESERVA_QUARTO ADD CONSTRAINT FK_RESERVA_QUARTO_PACOTE_VIAGEM
    FOREIGN KEY (id_pacote_viagem)
    REFERENCES PACOTE_VIAGEM (id);

ALTER TABLE RESERVA_QUARTO ADD CONSTRAINT FK_RESERVA_QUARTO_HOSPEDARIA
    FOREIGN KEY (id_hospedaria)
    REFERENCES HOSPEDARIA (id);

-- Adicionando as constraints para a tabela HOSPEDARIA
ALTER TABLE HOSPEDARIA ADD CONSTRAINT PK_HOSPEDARIA
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela TIPO_VEICULO
ALTER TABLE TIPO_VEICULO ADD CONSTRAINT PK_TIPO_VEICULO
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela RAMO_EMPRESA
ALTER TABLE RAMO_EMPRESA ADD CONSTRAINT PK_RAMO_EMPRESA
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela RESERVA_VEICULO
ALTER TABLE RESERVA_VEICULO ADD CONSTRAINT PK_RESERVA_VEICULO
    PRIMARY KEY (id);

ALTER TABLE RESERVA_VEICULO ADD CONSTRAINT FK_RESERVA_VEICULO_PACOTE_VIAGEM
    FOREIGN KEY (id_pacote_viagem)
    REFERENCES PACOTE_VIAGEM (id);

ALTER TABLE RESERVA_VEICULO ADD CONSTRAINT FK_RESERVA_VEICULO_TIPO_VEICULO
    FOREIGN KEY (id_tipo_veiculo)
    REFERENCES TIPO_VEICULO (id);

ALTER TABLE RESERVA_VEICULO ADD CONSTRAINT FK_RESERVA_VEICULO_EMPRESA
    FOREIGN KEY (id_empresa_locadora)
    REFERENCES EMPRESA (id);

-- Adicionando as constraints para a tabela PASSEIO
ALTER TABLE PASSEIO ADD CONSTRAINT PK_PASSEIO
    PRIMARY KEY (id);

ALTER TABLE PASSEIO ADD CONSTRAINT FK_PASSEIO_ENDERECO
    FOREIGN KEY (id_endereco)
    REFERENCES ENDERECO (id);

-- Adicionando as constraints para a tabela ENDERECO
ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO
    PRIMARY KEY (id);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_CIDADE
    FOREIGN KEY (id_cidade)
    REFERENCES CIDADE (id);

-- Adicionando as constraints para a tabela CIDADE
ALTER TABLE CIDADE ADD CONSTRAINT PK_CIDADE
    PRIMARY KEY (id);

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_ESTADO
    FOREIGN KEY (id_estado)
    REFERENCES ESTADO (id);

-- Adicionando as constraints para a tabela ESTADO
ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela BENEFICIO_HOSPEDAGEM
ALTER TABLE BENEFICIO_HOSPEDAGEM ADD CONSTRAINT PK_BENEFICIO_HOSPEDAGEM
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela PASSAGEM_AEREA
ALTER TABLE PASSAGEM_AEREA ADD CONSTRAINT PK_PASSAGEM_AEREA
    PRIMARY KEY (id);

ALTER TABLE PASSAGEM_AEREA ADD CONSTRAINT FK_PASSAGEM_AEREA_CLIENTE_TITULAR
    FOREIGN KEY (id_cliente_titular)
    REFERENCES CLIENTE (id);

ALTER TABLE PASSAGEM_AEREA ADD CONSTRAINT FK_PASSAGEM_AEREA_COMPANHIA_AEREA
    FOREIGN KEY (id_companhia_aerea)
    REFERENCES EMPRESA (id);

-- Adicionando as constraints para a tabela TIPO_DOCUMENTO
ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT PK_TIPO_DOCUMENTO
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela TIPO_NECESSIDADE_ESPECIAL
ALTER TABLE TIPO_NECESSIDADE_ESPECIAL ADD CONSTRAINT PK_TIPO_NECESSIDADE_ESPECIAL
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela CLIENTE
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela TIPO_CONTATO
ALTER TABLE TIPO_CONTATO ADD CONSTRAINT PK_TIPO_CONTATO
    PRIMARY KEY (id);
    
-- Adicionando as constraints para a tabela STATUS
ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS
    PRIMARY KEY (id);

-- Adicionando as constraints para a tabela PAGAMENTO
ALTER TABLE PAGAMENTO ADD CONSTRAINT PK_PAGAMENTO
    PRIMARY KEY (id);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_METODO_PAGAMENTO
    FOREIGN KEY (id_metodo_pagamento)
    REFERENCES METODO_PAGAMENTO (id);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_PACOTE_VIAGEM
    FOREIGN KEY (id_pacote_viagem)
    REFERENCES PACOTE_VIAGEM (id);

-- Adicionando as constraints para a tabela METODO_PAGAMENTO
ALTER TABLE METODO_PAGAMENTO ADD CONSTRAINT PK_METODO_PAGAMENTO
    PRIMARY KEY (id);
    
-- Adicionando as constraints para a tabela EMPRESA_VEICULO
ALTER TABLE EMPRESA_VEICULO ADD CONSTRAINT FK_EMPRESA_VEICULO_EMPRESA
    FOREIGN KEY (id_empresa)
    REFERENCES EMPRESA (id);

ALTER TABLE EMPRESA_VEICULO ADD CONSTRAINT FK_EMPRESA_VEICULO_TIPO_VEICULO
    FOREIGN KEY (id_tipo_veiculo)
    REFERENCES TIPO_VEICULO (id);

-- Adicionando as constraints para a tabela BENEFICIO_HOSPEDARIA
ALTER TABLE BENEFICIO_HOSPEDARIA ADD CONSTRAINT FK_Oferece_HOSPEDARIA
    FOREIGN KEY (id_hospedaria)
    REFERENCES HOSPEDARIA (id);

ALTER TABLE BENEFICIO_HOSPEDARIA ADD CONSTRAINT FK_Oferece_BENEFICIO_HOSPEDAGEM
    FOREIGN KEY (id_beneficio_hospedagem)
    REFERENCES BENEFICIO_HOSPEDAGEM (id);

-- Adicionando as constraints para a tabela EMPRESA_PASSEIO
ALTER TABLE EMPRESA_PASSEIO ADD CONSTRAINT FK_EMPRESA_PASSEIO_PASSEIO
    FOREIGN KEY (id_passeio)
    REFERENCES PASSEIO (id);

ALTER TABLE EMPRESA_PASSEIO ADD CONSTRAINT FK_EMPRESA_PASSEIO_EMPRESA
    FOREIGN KEY (id_empresa)
    REFERENCES EMPRESA (id);
    
-- Adicionando as constraints para a tabela PASSAGEM_AEREA_VIAGEM
ALTER TABLE PASSAGEM_AEREA_VIAGEM ADD CONSTRAINT FK_PASSAGEM_AEREA_VIAGEM_PACOTE_VIAGEM
    FOREIGN KEY (id_pacote_viagem)
    REFERENCES PACOTE_VIAGEM (id);

ALTER TABLE PASSAGEM_AEREA_VIAGEM ADD CONSTRAINT FK_PASSAGEM_AEREA_VIAGEM_PASSAGEM_AEREA
    FOREIGN KEY (id_passagem_aerea)
    REFERENCES PASSAGEM_AEREA (id);

-- Adicionando as constraints para a tabela DOCUMENTO_CLIENTE
ALTER TABLE DOCUMENTO_CLIENTE ADD CONSTRAINT FK_DOCUMENTO_CLIENTE_TIPO_DOCUMENTO
    FOREIGN KEY (id_tipo_documento)
    REFERENCES TIPO_DOCUMENTO (id);

ALTER TABLE DOCUMENTO_CLIENTE ADD CONSTRAINT FK_DOCUMENTO_CLIENTE_CLIENTE
    FOREIGN KEY (id_cliente)
    REFERENCES CLIENTE (id);

-- Adicionando as constraints para a tabela NECESSIDADE_ESPECIAL_CLIENTE
ALTER TABLE NECESSIDADE_ESPECIAL_CLIENTE ADD CONSTRAINT FK_NECESSIDADE_ESPECIAL_CLIENTE_CLIENTE
    FOREIGN KEY (id_cliente)
    REFERENCES CLIENTE (id);

ALTER TABLE NECESSIDADE_ESPECIAL_CLIENTE ADD CONSTRAINT FK_NECESSIDADE_ESPECIAL_CLIENTE_NECESSIDADE_ESPECIAL
    FOREIGN KEY (id_necessidade_especial)
    REFERENCES TIPO_NECESSIDADE_ESPECIAL (id);

-- Adicionando as constraints para a tabela CONTATO_CLIENTE_RESPONSAVEL
ALTER TABLE CONTATO_CLIENTE_RESPONSAVEL ADD CONSTRAINT FK_CONTATO_CLIENTE_RESPONSAVEL_TIPO_CONTATO
    FOREIGN KEY (id_tipo_contato)
    REFERENCES TIPO_CONTATO (id);

ALTER TABLE CONTATO_CLIENTE_RESPONSAVEL ADD CONSTRAINT FK_CONTATO_CLIENTE_RESPONSAVEL_CLIENTE
    FOREIGN KEY (id_cliente)
    REFERENCES CLIENTE (id);
    
-- Adicionando as constraints para a tabela AGENDA_PASSEIO_VIAGEM
ALTER TABLE AGENDA_PASSEIO_VIAGEM ADD CONSTRAINT FK_AGENDA_PASSEIO_VIAGEM_PACOTE_VIAGEM
    FOREIGN KEY (id_pacote_viagem)
    REFERENCES PACOTE_VIAGEM (id);

ALTER TABLE AGENDA_PASSEIO_VIAGEM ADD CONSTRAINT FK_AGENDA_PASSEIO_VIAGEM_PASSEIO
    FOREIGN KEY (id_passeio)
    REFERENCES PASSEIO (id);

-- Adicionando as constraints para a tabela CONTATO_EMPRESA
ALTER TABLE CONTATO_EMPRESA ADD CONSTRAINT FK_CONTATO_EMPRESA_TIPO_CONTATO
    FOREIGN KEY (id_tipo_contato)
    REFERENCES TIPO_CONTATO (id);

ALTER TABLE CONTATO_EMPRESA ADD CONSTRAINT FK_CONTATO_EMPRESA_EMPRESA
    FOREIGN KEY (id_empresa)
    REFERENCES EMPRESA (id);

-- Adicionando as constraints para a tabela ACOMPANHANTE_VIAGEM
ALTER TABLE ACOMPANHANTE_VIAGEM ADD CONSTRAINT FK_ACOMPANHANTE_VIAGEM_CLIENTE
    FOREIGN KEY (id_cliente)
    REFERENCES CLIENTE (id);

ALTER TABLE ACOMPANHANTE_VIAGEM ADD CONSTRAINT FK_ACOMPANHANTE_VIAGEM_SOLICITACAO_VIAGEM
    FOREIGN KEY (id_solicitacao_viagem)
    REFERENCES SOLICITACAO_VIAGEM (id);

-- Adicionando as constraints para a tabela SITUACAO_ATENDIMENTO
ALTER TABLE SITUACAO_ATENDIMENTO ADD CONSTRAINT FK_SITUACAO_ATENDIMENTO_SOLICITACAO_VIAGEM
    FOREIGN KEY (id_solicitacao_viagem)
    REFERENCES SOLICITACAO_VIAGEM (id);

ALTER TABLE SITUACAO_ATENDIMENTO ADD CONSTRAINT FK_SITUACAO_ATENDIMENTO_STATUS
    FOREIGN KEY (id_status)
    REFERENCES STATUS (id);

-- Adicionando as constraints para a tabela PROCURA_VEICULO_VIAGEM
ALTER TABLE PROCURA_VEICULO_VIAGEM ADD CONSTRAINT FK_PROCURA_VEICULO_VIAGEM_TIPO_VEICULO
    FOREIGN KEY (id_tipo_veiculo)
    REFERENCES TIPO_VEICULO (id);

ALTER TABLE PROCURA_VEICULO_VIAGEM ADD CONSTRAINT FK_PROCURA_VEICULO_VIAGEM_SOLICITACAO_VIAGEM
    FOREIGN KEY (id_solicitacao_viagem)
    REFERENCES SOLICITACAO_VIAGEM (id);

COMMIT;